---
title: "CV-Timeline"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

list.of.packages <- c("lares", "ggplot2")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)){ 
  install.packages("ggplot2")
  
  devtools::install_github("laresbernardo/lares")
}


# All packages used below must be installed first
library(devtools)
library(lares)
library(ggplot2)
```

```{r}


plot_timeline2 <- function(event, start, end = start + 1, label = NA, group = NA,
                           title = "", subtitle = "Shruti Hegde",
                           size = 7, colour = "orange", save = FALSE, subdir = NA) {
  df <- data.frame(
    Role = as.character(event), Place = as.character(label),
    Start = lubridate::date(start), End = lubridate::date(end),
    Type = group
  )
  cvlong <- data.frame(pos = rep(
    as.numeric(rownames(df)),
    2
  ), name = rep(as.character(df$Role), 2), type = rep(factor(df$Type,
    ordered = TRUE
  ), 2), where = rep(
    as.character(df$Place),
    2
  ), value = c(df$Start, df$End), label_pos = rep(df$Start +
    floor((df$End - df$Start) / 2), 2))
  maxdate <- max(df$End)
  p <- ggplot(cvlong, aes(
    x = value, y = reorder(name, -pos),
    label = where, group = pos
  )) + geom_vline(
    xintercept = maxdate,
    alpha = 0.8, linetype = "dotted"
  ) + labs(
    title = title,
    subtitle = subtitle, x = NULL, y = NULL, colour = NULL
  ) +
    theme_lares2() + theme(panel.background = element_rect(
      fill = "white",
      colour = NA
    ), axis.ticks = element_blank(), panel.grid.major.x = element_line(
      size = 0.25,
      colour = "grey80"
    ))
  if (!is.na(cvlong$type)[1] | length(unique(cvlong$type)) >
    1) {
    p <- p + geom_line(aes(color = type), size = size) +
      facet_grid(type ~ ., scales = "free", space = "free") +
      guides(colour = FALSE) +
      scale_colour_hue()
  }
  else {
    p <- p + geom_line(size = size, colour = colour)
  }
  p <- p + geom_label(aes(x = label_pos),
    colour = "black",
    size = 3, alpha = 0.7, nudge_y = 0.25
  )
  if (save) {
    file_name <- "cv_timeline.png"
    if (!is.na(subdir)) {
      dir.create(file.path(getwd(), subdir), recursive = T)
      file_name <- paste(subdir, file_name, sep = "/")
    }
    p <- p + ggsave(file_name, width = 14, height = 10)
    message(paste("Saved plot as", file_name))
  }
  return(p)
}

order <- c("Role", "Place", "Type", "Start", "End")
today <- as.character(Sys.Date())


### Edit from here ###
cv <- data.frame(rbind(
  c("PhD in Chemical Engineering", "University of Utah", "Academic", "2016-01-01", "2020-05-01"),
  c("BS in Chemical Engineering", "Dayananda Sagar College of Engineering", "Academic", "2013-06-01", "2009-06-01"),
  
  c("Graduate Research Assistant", "University of Utah", "Research Experience", "2016-08-01", today),
  c("Research Assistant", "Indian Institute of Science", "Research Experience", "2013-09-01", "2015-06-01"),
  c("Undergraduate Researcher", "Indian Institute of Science", "Research Experience", "2013-02-01", "2013-06-01")
))
### Edit until here ###


colnames(cv) <- order
colour <- c("red", "blue", "green")

plot_timeline2(
  event = cv$Role,
  start = cv$Start,
  end = cv$End,
  label = cv$Place,
  group = cv$Type,
  save = FALSE 
)
```


