name: Refresh Resume

on:
  push:
    branches: [ dev ]
    paths:
    - 'shruti-hegde/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: rocker/verse

    steps:
    - uses: actions/checkout@v2
    
    - name: Install R packages
      run: Rscript -e 'install.packages(c("vitae", "here"))'
    - name: Render Resume
      run: Rscript -e 'rmarkdown::render("shruti-hegde/shruti-hegde.Rmd")'
    - name: Commit pdf 
      run: |
        mv shruti-hegde/shruti-hegde.pdf shruti-hegde-cv.pdf
        git config user.name "shrutigo"
        git config user.email "shrutigo@gmail.com"
        git add  shruti-hegde-cv.pdf || echo "No changes to commit"
        git commit shruti-hegde-cv.pdf -m "Auto re-build resume.pdf file" || echo "No changes to commit"
        git push origin || echo "No changes to commit"